import type { LucideIcon } from "lucide-react";
import {
  Activity,
  ArrowRight,
  BarChart3,
  BadgeCheck,
  BookOpen,
  BriefcaseBusiness,
  Building2,
  CalendarDays,
  CircleCheck,
  Cloud,
  Code2,
  Database,
  GraduationCap,
  Globe2,
  HandHeart,
  Headphones,
  Hotel,
  Layers3,
  Lightbulb,
  MonitorSmartphone,
  Mail,
  MapPin,
  Palette,
  PawPrint,
  Phone,
  Rocket,
  Search,
  Server,
  Settings2,
  ShieldCheck,
  ShoppingCart,
  ShoppingBag,
  Sparkles,
  Target,
  TestTube2,
  Users,
  Workflow,
} from "lucide-react";

import type { IconName } from "@/content/types";

const iconMap: Record<IconName, LucideIcon> = {
  activity: Activity,
  analytics: BarChart3,
  api: Workflow,
  "arrow-right": ArrowRight,
  "badge-check": BadgeCheck,
  "book-open": BookOpen,
  briefcase: BriefcaseBusiness,
  building: Building2,
  calendar: CalendarDays,
  "check-circle": CircleCheck,
  cloud: Cloud,
  code: Code2,
  database: Database,
  "device-mobile": MonitorSmartphone,
  globe: Globe2,
  "graduation-cap": GraduationCap,
  "heart-handshake": HandHeart,
  headphones: Headphones,
  hotel: Hotel,
  layers: Layers3,
  lightbulb: Lightbulb,
  mail: Mail,
  "map-pin": MapPin,
  palette: Palette,
  "paw-print": PawPrint,
  phone: Phone,
  rocket: Rocket,
  search: Search,
  server: Server,
  settings: Settings2,
  "shield-check": ShieldCheck,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  sparkles: Sparkles,
  target: Target,
  "test-tube": TestTube2,
  users: Users,
  workflow: Workflow,
};

export function getContentIcon(name: IconName): LucideIcon {
  return iconMap[name] ?? Code2;
}
