import type { Service } from "./types";

const serviceMeta = {
  verification: "unverified",
  source: "project-brief",
  published: true,
  note: "Service scope comes from the project brief and should be confirmed before making contractual claims.",
} as const;

export const services = [
  {
    slug: "custom-software-development",
    title: "Custom Software Development",
    shortTitle: "Custom Software",
    description: "Purpose-built software shaped around a business workflow, user need, or operational challenge.",
    icon: "code",
    keyCapabilities: ["Business workflow modelling", "Role-based applications", "Scalable product architecture"],
    technologies: [],
    relatedPortfolioSlugs: [],
    cta: { label: "Discuss Custom Software", href: "/contact?project=custom-software-development", variant: "text" },
    ...serviceMeta,
  },
  {
    slug: "web-development",
    title: "Web Application Development",
    shortTitle: "Web Development",
    description: "Responsive web applications designed for clear user journeys, maintainability, and performance.",
    icon: "globe",
    keyCapabilities: ["Responsive frontends", "Application interfaces", "Content and data integration"],
    technologies: [],
    relatedPortfolioSlugs: [],
    cta: { label: "Discuss Web Development", href: "/contact?project=web-application-development", variant: "text" },
    ...serviceMeta,
  },
  {
    slug: "e-commerce-development",
    title: "E-Commerce Website Development",
    shortTitle: "E-Commerce",
    description: "Commerce experiences for product discovery, customer accounts, checkout, and store operations.",
    icon: "shopping-cart",
    keyCapabilities: ["Product catalogues", "Cart and checkout flows", "Order and inventory workflows"],
    technologies: [],
    relatedPortfolioSlugs: [],
    cta: { label: "Discuss E-Commerce", href: "/contact?project=e-commerce-website-development", variant: "text" },
    ...serviceMeta,
  },
  {
    slug: "hotel-management-systems",
    title: "Hotel Management Systems",
    shortTitle: "Hotel Systems",
    description: "Digital tools for hospitality booking, guest, room, billing, housekeeping, and reporting workflows.",
    icon: "hotel",
    keyCapabilities: ["Booking and availability", "Guest and room operations", "Billing and operational reporting"],
    technologies: [],
    relatedPortfolioSlugs: [],
    cta: { label: "Discuss Hotel Systems", href: "/contact?project=hotel-management-system", variant: "text" },
    ...serviceMeta,
  },
  {
    slug: "static-business-websites",
    title: "Static Business Websites",
    shortTitle: "Business Websites",
    description: "Focused business websites structured to communicate services, credibility, and clear calls to action.",
    icon: "globe",
    keyCapabilities: ["Responsive page systems", "Content-led layouts", "Search-friendly foundations"],
    technologies: [],
    relatedPortfolioSlugs: [],
    cta: { label: "Discuss a Business Website", href: "/contact?project=static-business-website", variant: "text" },
    ...serviceMeta,
  },
  {
    slug: "pet-shop-websites",
    title: "Pet Shop Websites",
    shortTitle: "Pet Commerce",
    description: "Pet retail and service experiences that can combine products, pet profiles, bookings, and subscriptions.",
    icon: "paw-print",
    keyCapabilities: ["Pet product catalogues", "Pet profiles", "Service and appointment booking"],
    technologies: [],
    relatedPortfolioSlugs: [],
    cta: { label: "Discuss Pet Commerce", href: "/contact?project=pet-shop-website", variant: "text" },
    ...serviceMeta,
  },
  {
    slug: "mobile-app-development",
    title: "Mobile Application Development",
    shortTitle: "Mobile Apps",
    description: "Mobile product experiences designed around focused tasks, clear navigation, and device-appropriate interaction.",
    icon: "device-mobile",
    keyCapabilities: ["Mobile product design", "Application development", "API-connected experiences"],
    technologies: [],
    relatedPortfolioSlugs: [],
    cta: { label: "Discuss a Mobile App", href: "/contact?project=mobile-application-development", variant: "text" },
    ...serviceMeta,
  },
  {
    slug: "ui-ux-design",
    title: "UI/UX Design",
    shortTitle: "UI/UX Design",
    description: "Research-informed interfaces and reusable design systems for understandable, accessible product experiences.",
    icon: "palette",
    keyCapabilities: ["User flows and wireframes", "Interface design", "Prototypes and design systems"],
    technologies: [],
    relatedPortfolioSlugs: [],
    cta: { label: "Discuss Product Design", href: "/contact?project=ui-ux-design", variant: "text" },
    ...serviceMeta,
  },
  {
    slug: "api-development",
    title: "API Development and Integrations",
    shortTitle: "APIs & Integrations",
    description: "Interfaces that connect approved applications, data sources, and third-party services.",
    icon: "api",
    keyCapabilities: ["API design", "Third-party integrations", "Data exchange workflows"],
    technologies: [],
    relatedPortfolioSlugs: [],
    cta: { label: "Discuss an Integration", href: "/contact?project=api-development-or-integration", variant: "text" },
    ...serviceMeta,
  },
  {
    slug: "cloud-devops",
    title: "Cloud and DevOps",
    shortTitle: "Cloud & DevOps",
    description: "Deployment and operational foundations planned around the product’s reliability and delivery needs.",
    icon: "cloud",
    keyCapabilities: ["Deployment planning", "Environment configuration", "Delivery automation"],
    technologies: [],
    relatedPortfolioSlugs: [],
    cta: { label: "Discuss Cloud Delivery", href: "/contact?project=cloud-solution", variant: "text" },
    ...serviceMeta,
  },
  {
    slug: "quality-assurance",
    title: "Quality Assurance",
    shortTitle: "Quality Assurance",
    description: "Structured testing intended to identify functional, compatibility, usability, and performance issues.",
    icon: "test-tube",
    keyCapabilities: ["Functional testing", "Cross-device validation", "Regression and release checks"],
    technologies: [],
    relatedPortfolioSlugs: [],
    cta: { label: "Discuss Quality Assurance", href: "/contact?project=quality-assurance", variant: "text" },
    ...serviceMeta,
  },
  {
    slug: "maintenance-support",
    title: "Maintenance and Support",
    shortTitle: "Support",
    description: "Post-launch maintenance planning for fixes, updates, monitoring, and product improvements.",
    icon: "headphones",
    keyCapabilities: ["Issue resolution", "Product updates", "Ongoing enhancement planning"],
    technologies: [],
    relatedPortfolioSlugs: [],
    cta: { label: "Discuss Ongoing Support", href: "/contact?project=maintenance-and-support", variant: "text" },
    ...serviceMeta,
  },
] as const satisfies readonly Service[];

export const serviceTechnologiesNote =
  "Technology lists are intentionally empty until Qorvexa confirms the supported stack for each service.";

export const serviceEngagementModels = [
  {
    slug: "project-based",
    title: "Project-Based",
    description: "A scoped engagement model represented in the design brief.",
    verification: "unverified",
    source: "project-brief",
    published: false,
  },
  {
    slug: "dedicated-team",
    title: "Dedicated Team",
    description: "A team-extension model represented in the design brief.",
    verification: "unverified",
    source: "project-brief",
    published: false,
  },
  {
    slug: "retainer-support",
    title: "Retainer Support",
    description: "An ongoing support model represented in the design brief.",
    verification: "unverified",
    source: "project-brief",
    published: false,
  },
] as const;

export const getServiceBySlug = (slug: string) =>
  services.find((service) => service.slug === slug);
