import { solutionAssets } from "./assets";
import type { Solution } from "./types";

const solutionMeta = {
  verification: "unverified",
  source: "project-brief",
  published: true,
  note: "Industry descriptions are planning content from the project brief, not verified client claims.",
} as const;

export const solutions = [
  {
    slug: "e-commerce-retail",
    title: "E-Commerce and Retail",
    description: "Customer-facing commerce and operational tools for retailers and product businesses.",
    challenge: "Bring product discovery, purchasing, orders, and inventory into a coherent digital flow.",
    proposedSolution: "A responsive commerce experience connected to practical store-management workflows.",
    features: ["Product catalogue and search", "Checkout and order tracking", "Inventory and customer management"],
    icon: "shopping-cart",
    image: solutionAssets.ecommerceRetail,
    cta: { label: "Discuss a Retail Solution", href: "/contact?solution=e-commerce-retail", variant: "text" },
    ...solutionMeta,
  },
  {
    slug: "hotel-hospitality",
    title: "Hotel and Hospitality",
    description: "Booking, guest, room, and operational experiences for hospitality businesses.",
    challenge: "Connect guest-facing reservations with the day-to-day work behind each stay.",
    proposedSolution: "A modular hospitality platform for availability, bookings, guests, rooms, billing, and operations.",
    features: ["Direct bookings and reservations", "Guest and room workflows", "Housekeeping and reporting"],
    icon: "hotel",
    image: solutionAssets.hotelHospitality,
    cta: { label: "Discuss a Hospitality Solution", href: "/contact?solution=hotel-hospitality", variant: "text" },
    ...solutionMeta,
  },
  {
    slug: "pet-care-stores",
    title: "Pet Care and Pet Stores",
    description: "Digital commerce and service workflows for pet products, profiles, appointments, and care services.",
    challenge: "Support both retail purchases and pet-specific service journeys in one understandable experience.",
    proposedSolution: "A pet commerce platform that combines catalogue, pet profiles, bookings, and subscriptions.",
    features: ["Pet profiles", "Products and subscriptions", "Appointments and grooming services"],
    icon: "paw-print",
    image: solutionAssets.petCareStores,
    cta: { label: "Discuss a Pet-Care Solution", href: "/contact?solution=pet-care-stores", variant: "text" },
    ...solutionMeta,
  },
  {
    slug: "corporate-websites",
    title: "Corporate Websites",
    description: "Professional websites structured around credibility, services, content, and conversion paths.",
    challenge: "Explain a business clearly while making relevant information easy to find and maintain.",
    proposedSolution: "A responsive, content-led website system with focused journeys and reusable page patterns.",
    features: ["Service and company content", "Lead-generation forms", "Maintainable content structure"],
    icon: "building",
    image: solutionAssets.corporateWebsites,
    cta: { label: "Discuss a Corporate Website", href: "/contact?solution=corporate-websites", variant: "text" },
    ...solutionMeta,
  },
  {
    slug: "service-booking",
    title: "Service Booking",
    description: "Scheduling and reservation experiences for businesses that sell time-based services.",
    challenge: "Make availability, selection, booking, and administration understandable to customers and operators.",
    proposedSolution: "A responsive booking platform with customer flows and configurable operational controls.",
    features: ["Availability and scheduling", "Provider and slot management", "Booking notifications"],
    icon: "calendar",
    image: solutionAssets.serviceBooking,
    cta: { label: "Discuss a Booking Solution", href: "/contact?solution=service-booking", variant: "text" },
    ...solutionMeta,
  },
  {
    slug: "internal-business-software",
    title: "Internal Business Software",
    description: "Custom dashboards and workflows for teams, tasks, data, and business operations.",
    challenge: "Replace fragmented operational steps with a secure and understandable system.",
    proposedSolution: "Role-aware software tailored to the organization’s approved workflows and reporting needs.",
    features: ["Workflow automation", "Role-based access", "Dashboards and reporting"],
    icon: "workflow",
    image: solutionAssets.internalSoftware,
    cta: { label: "Discuss Internal Software", href: "/contact?solution=internal-business-software", variant: "text" },
    ...solutionMeta,
  },
  {
    slug: "healthcare",
    title: "Healthcare",
    description: "A solution category reserved for approved healthcare workflows and user experiences.",
    challenge: "Healthcare requirements vary and may involve sensitive data, accessibility, and regulatory obligations.",
    proposedSolution: "Scope the workflow and applicable requirements before proposing architecture or features.",
    features: ["Requirements discovery", "Accessible user flows", "Security and compliance planning"],
    icon: "heart-handshake",
    image: solutionAssets.healthcare,
    cta: { label: "Discuss a Healthcare Brief", href: "/contact?solution=healthcare", variant: "text" },
    ...solutionMeta,
  },
  {
    slug: "education",
    title: "Education",
    description: "A solution category for learning, administration, and education-focused digital experiences.",
    challenge: "Different learners and administrators need clear access to content, tasks, and progress information.",
    proposedSolution: "Define the audience and learning workflow before selecting features or delivery technology.",
    features: ["Learning journeys", "Content and resource access", "Administrative workflows"],
    icon: "graduation-cap",
    image: solutionAssets.education,
    cta: { label: "Discuss an Education Brief", href: "/contact?solution=education", variant: "text" },
    ...solutionMeta,
  },
  {
    slug: "real-estate",
    title: "Real Estate",
    description: "A solution category for property discovery, enquiries, listings, and operational workflows.",
    challenge: "Present property information clearly while supporting search, enquiries, and internal follow-up.",
    proposedSolution: "A structured property experience shaped around the approved listing and lead workflow.",
    features: ["Property search and filters", "Listing presentation", "Enquiry workflows"],
    icon: "building",
    image: solutionAssets.realEstate,
    cta: { label: "Discuss a Real-Estate Brief", href: "/contact?solution=real-estate", variant: "text" },
    ...solutionMeta,
  },
  {
    slug: "professional-services",
    title: "Professional Services",
    description: "Web, booking, and operational experiences for expertise-led service businesses.",
    challenge: "Communicate expertise while creating a direct path from interest to enquiry or booking.",
    proposedSolution: "A focused service platform with clear content, conversion paths, and approved operational integrations.",
    features: ["Service presentation", "Lead or booking flows", "Content and operational integrations"],
    icon: "briefcase",
    image: solutionAssets.professionalServices,
    cta: { label: "Discuss a Services Platform", href: "/contact?solution=professional-services", variant: "text" },
    ...solutionMeta,
  },
] as const satisfies readonly Solution[];

export const crossSolutionFeatures = [
  { title: "Dashboard and Analytics", icon: "analytics" },
  { title: "Booking Workflows", icon: "calendar" },
  { title: "Payments", icon: "shopping-cart" },
  { title: "Inventory Workflows", icon: "database" },
  { title: "Customer Data", icon: "users" },
  { title: "Reports and Insights", icon: "activity" },
  { title: "Responsive Interfaces", icon: "device-mobile" },
] as const;

export const getSolutionBySlug = (slug: string) =>
  solutions.find((solution) => solution.slug === slug);
